name: lua
favicon: null
layout_spectrum: 0.01330360327847302
typography_spectrum: 0.07505181431770325
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.2594457510858774
purpose:
  - name: shares
    item: null
    url: null
